pipeline:
  dry_run: false
  continue_on_error: true

stages:
  - name: parse
    args:
      clean_outdir: true
      inputs_glob:
        - "docs/*.pdf"
        - "docs/*.docx"
        - "docs/*.png"
        - "docs/*.jpg"
      outdir: "outputs_ir"

  - name: contextize-doc
    args:
      clean_outdir: true
      ir_glob: "outputs_ir/*.json"
      embedding_model: "all-MiniLM-L6-v2"
      nr_topics: null     # null → None
      seed: 42
      cache_dir: ".cache_embeddings"   # opcional, si quieres caching
      outdir: "outputs_doc_topics"
