pipeline:
  dry_run: false
  continue_on_error: true

stages:
  - name: parse
    args:
      clean_outdir: true
      inputs_glob:
        - "docs/*.pdf"
        - "docs/*.docx"
        - "docs/*.png"
        - "docs/*.jpg"
        - "docs/*.csv"
      outdir: "outputs_ir"

  - name: contextize-doc
    args:
      clean_outdir: true
      ir_glob: "outputs_ir/*.json"
      embedding_model: "all-MiniLM-L6-v2"
      nr_topics: null
      seed: 42
      outdir: "outputs_doc_topics"

  - name: chunk
    args:
      clean_outdir: true
      ir_glob: "outputs_doc_topics/*.json"
      outdir: "outputs_chunks"
      max_tokens: 2048
      min_chars: 280
      use_embeddings: true
      embedding_model: "all-MiniLM-L6-v2"
      spacy_model: "es_core_news_sm"
      seed: 42

  - name: contextize-chunks
    args:
      chunks_glob: "outputs_chunks/*.json"
      embedding_model: "all-MiniLM-L6-v2"
      nr_topics: null
      seed: 42
      outdir: "outputs_chunks"   # sobrescribe en sitio

  - name: schema-select
    args:
      chunks_glob: "outputs_chunks/*.json"
      outdir: "outputs_schema"
      clean_outdir: true

      # --- Pesos de señales ---
      alpha_kw: 0.30       # Keywords (léxica)
      beta_emb: 0.25       # Embeddings (semántica densa)
      gamma_ctx: 0.25      # Métricas contextuales (cohesión, health, novelty)
      delta_top: 0.15      # Afinidad de tópicos globales/locales
      epsilon_prior: 0.05  # Priors (sesgos organizacionales)

      # --- Umbrales y control ---
      ambig_threshold: 0.12        # Diferencia mínima para marcar ambigüedad
      fallback_threshold: 0.40     # Confianza mínima antes de fallback genérico
      softmax_temp: 0.85           # Temperatura del softmax (confianza)
      disable_generic: false       # Si true, no aplica fallback 'generic'

      # --- Selección de dominios ---
      topk_domains: 5              # Cuántos dominios devuelve a nivel doc
      max_domains: 5               # Máximo de dominios evaluados
